### ISSUE TITLE
Configurable download location?

### ISSUE THREAD

**Issue by aleksandar-todorovic** [deathau/markdown-clipper#13]
**Current workflow:**

1. Go to a page.
2. Click on the extension.
3. Click on "download".
4. Move from your downloads folder to your preferred location (way too many clicks).

**Proposed workflow:**

1. Have the configurable download location (example: `~/notes/articles`)
2. Find an article.
3. Click on the extension.
4. Click on "download".
5. The file gets automatically put in the right location.

To be honest I have no idea if it's possible to do this with the add-ons, but it would definitely save seconds each time I want to trigger the add-on.

**Comment by deathau** [comment]
I've had a bit of a look into this, and I don't think it's possible, unfortunately.
I can specify whether or not to show the Save As dialog, and if I specify not, it will just do whatever the browser does by default - which could be the Save As dialog, or just download to the downloads folder. See [this link](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/download#Parameters:~:text=If%20this%20option%20is%20omitted%2C%20the,general%20user%20preference%20for%20this%20behavior).
I can specify a path, but it will be relative to the downloads folder, unfortunately. [Absolute paths, empty paths, and paths containing back-references (../) will cause an error](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/download#Parameters:~:text=Absolute%20paths%2C%20empty%20paths%2C%20and%20paths%20containing%20back%2Dreferences%20(..%2F)%20will%20cause%20an%20error.)
