### ISSUE TITLE
Allow to save as or copy to clipboard from the right click menu and keyboard shortcut

### ISSUE THREAD

**Issue by bs** [deathau/markdown-clipper#17]
I very often want to snip something for my personal notes. Would be amazing to have a keyboard shortcut to activate the dialog, as well as being able to do so via right clicking!

Thanks for all your work!

**Comment by deathau** [comment]
I've now added a keyboard shortcut for opening the popup (alt+shift+M by default), and I've added some right-click options for copying and downloading markdown. Unfortunately, these right-click options bypass the popup, as there's no way to activate the popup from a background script...
