### ISSUE TITLE
Feature request: choose the default directory to download

### ISSUE THREAD

**Issue by ddfonseca** [deathau/markdown-clipper#20]
Hi, thank you for making this wonderful extension! I really love it.

Since I'm using Obsidian markdown, it'll be even easier to extract the contents of web directly to my vault if I could choose where to download the files.

Thanks

**Comment by deathau** [comment]
Thanks for the feedback!
If you open the extension settings and scroll all the way down the bottom there's a newish option for always showing the Save As modal (instead of the browser's default behaviour). Hope this helps!

**Comment by ddfonseca** [comment]
> Thanks for the feedback!
> If you open the extension settings and scroll all the way down the bottom there's a newish option for always showing the Save As modal (instead of the browser's default behaviour). Hope this helps!

Sorry, I think I didn't explain correctly my feature request. I'd like to choose the default path for not having to choose everytime I click on download, despite being just one more click, it'll be like Notion/Pocket/Instapaper webclipper.

**Comment by ddfonseca** [comment]
And of course, I don't want all the downloads going directly to my vault on Obsidian....

**Comment by deathau** [comment]
Ah, I see. I've had a couple of requests for this, but unfortunately, the browser doesn't let the extension access the filesystem (due to security concerns) so there's no way for me to implement choosing of the download folder. Sadly, I can only respect the browser default or open the Save As modal.

**Comment by ddfonseca** [comment]
Hmm really? I didn't know. But what about open link? Since the last update of [Obsidian 0.9.0](https://forum.obsidian.md/t/obsidian-release-v0-9-0/5975) we can open a note directly on Obsidian with: **obsidian://open?vault=myvault&file=mynote** will open the file “mynote” inside the vault “myvault”. So, could we copy on clippboard the contents and open note on Obsidian?

**Comment by deathau** [comment]
That's a good idea and probably worth opening another issue for, but I have two issues with it:
- Obsidian doesn't have a URL scheme for creating notes or adding content, and I assume in most cases the note you're trying to clip doesn't exist in your vault yet, so I don't think it's possible. 
- Secondly, this extension isn't Obsidian-specific (as much as it comes from my desire to help the Obsidian community, Obsidian isn't the only use case for clipping markdown notes). That being said, if in the future Obsidian does get the ability to create notes via the URL scheme, I will most likely add more options for clipping directly to Obsidian, and/or fork this extension into a specific Obsidian clipper.

**Comment by ddfonseca** [comment]
Okoy... I agree with you, that's why just download directly to vault will be better, but that's is not an option. Thank you anyway!

**Comment by deathau** [comment]
I agree it would be better too. If and when it becomes possible in the future, it's something I will add.
