### ISSUE TITLE
Front-matter template option

### ISSUE THREAD

**Issue by deathau** [deathau/markdown-clipper#9]
Inspired by a discussion on the Obsidian discord: https://discord.com/channels/686053708261228577/700466324840775831/710709975219175465

Create, in the settings, a front-matter template whereby you specify which fields you want and the format they should take. For example:

```
---
URL: {url}
Author: {Author}
---
> {Excerpt}

# {Title}
```

**Comment by deathau** [comment]
Not sure what that would look like for fields like excerpt and author that may or may not exist though 🤔

**Comment by gabeguz** [comment]
I came looking for front matter support as well, I currently have 100s of notes in markdown format, but I'm using TOML front matter for all of them, looks like: 

```
+++
title = "vim for note taking"
tags = [ "vim", "notes", "zettelkasten" ]
+++
```

Would be really cool if obsidian could just read and parse these, and pull out my tags as well as the title + any other interesting metadata.
